config/routes.rb
Rails.application.routes.draw do
  get 'comments/edit'
  get 'horses/index'
  get 'horses/show'
  root to: "home#index"
  resource :user, only: %i(show), path: 'profile'
  devise_for :users
  resources :logs, only: %i(create new edit show destroy update)
  # resources :boards, only: %i(index new create show edit update destroy)
  resources :boards do
    resources :comments, only: %i(create destroy), shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { in: 4..127 }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :board

   validates :board, presence: true
   validates :comment, presence: true, length: { in: 1..1000 }
end

app/models/horse.rb
class Horse < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :logs
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    if @board.save
      redirect_to boards_path(@board)
    else
      render new
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.all
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to boards_path(@board)
    else
      render new
    end
  end

  def destroy
    @board = Board.find(params[:id])

    @board.destroy
    redirect_to boards_path
  end


    private
  def board_params
    params.require(:board).permit(%i(title))
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(comment_params)
  end

  def create
    @board = Board.find(params[:board_id])
    @comment = @board.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to board_path(@board)
    else 
      redirect_to board_path(@board)
    end
  end

  def edit
  end

    private

  def comment_params
    params.require(:comment).permit(%i(comment))
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  def index
    @horses = Horse.all
  end
end

app/controllers/log_controller.rb
class LogController < ApplicationController
  def index
  end

  def new
    @log = Log.new
  end

  def create
    @log = Log.new(log_params)
    if @log.save
      redirect_to user_path
    else 
      render 'new'
    end
  end

  private
  
  def log_params
    params.require(:log).permit(:diary)
  end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
  end

  def new
    @log = Log.new(log_params)
  end

  def create
    @log = Log.new(log_params)
    @log.user = current_user
    if @log.save
      redirect_to user_path
    else 
      render :new
    end
  end

  def destroy
    @log = Log.find(params[:id])
    if @log.destroy
      redirect_to user_path
    else 
      render :destroy
    end
  end

  private

  def log_params
    params.require(:log).permit(%i(diary))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @log = Log.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeibaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/partial/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/partial/_navbar.html.erb
 <h1>競馬チャンネル</h1>
 <nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        </button>
        <%= link_to 'TOP', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        <li><%= link_to 'データベース', horses_index_path %></li>
        <li><%= link_to '競馬広場', boards_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to 'マイページ', user_path %></li>
        <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>