config/routes.rb
Rails.application.routes.draw do
  get 'comments/edit'
  get 'horses/index'
  get 'horses/show'
  root to: "home#index"
  resource :user, only: %i(show), path: 'profile'
  devise_for :users
  resources :logs, only: %i(create new edit show destroy update)
  # resources :boards, only: %i(index new create show edit update destroy)
  resources :boards do
    resources :comments, only: %i(create destroy), shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { in: 4..127 }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :board

   validates :board, presence: true
   validates :comment, presence: true, length: { in: 1..1000 }
end

app/models/horse.rb
class Horse < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :logs
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    if @board.save
      redirect_to boards_path(@board)
    else
      render new
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.all
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to boards_path(@board)
    else
      render new
    end
  end

  def destroy
    @board = Board.find(params[:id])

    @board.destroy
    redirect_to boards_path
  end


    private
  def board_params
    params.require(:board).permit(%i(title))
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(comment_params)
  end

  def create
    @board = Board.find(params[:board_id])
    @comment = @board.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to board_path(@board)
    else 
      redirect_to board_path(@board)
    end
  end

  def edit
  end

    private

  def comment_params
    params.require(:comment).permit(%i(comment))
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  def index
    @horses = Horse.all
  end
end

app/controllers/log_controller.rb
class LogController < ApplicationController
  def index
  end

  def new
    @log = Log.new
  end

  def create
    @log = Log.new(log_params)
    if @log.save
      redirect_to user_path
    else 
      render 'new'
    end
  end

  private
  
  def log_params
    params.require(:log).permit(:diary)
  end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
  end

  def new
    @log = Log.new(log_params)
  end

  def create
    @log = Log.new(log_params)
    @log.user = current_user
    if @log.save
      redirect_to user_path
    else 
      render :new
    end
  end

  def destroy
    @log = Log.find(params[:id])
    if @log.destroy
      redirect_to user_path
    else 
      render :destroy
    end
  end

  private

  def log_params
    params.require(:log).permit(%i(diary))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @log = Log.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<%= link_to @board.title, board_path(@board.id) %>
<hr>
<h1>スレッド編集</h1>

<%= form_with model: @board, local: true do |f| %>
    <div class="field">
        <p><%= f.label :title %></p>
        <%= f.text_field :title %>
    </div>
    <div class="action">
        <%= f.submit %>
    </div>
<% end %>

app/views/boards/index.html.erb
 <%= link_to "スレッド新規作成", new_board_path %>

  <hr>
<div class="board">
      <% @boards.each do |board| %>
      <div class="board-content">
         <p><%= link_to board.title, board_path(board.id) %></p> 
      </div>
      <% end %>
</div>

app/views/boards/new.html.erb
 <%= link_to "スレッド一覧に戻る", boards_path %>
 <hr>
 <h1>スレッドを作成する</h1>
 <div>
    <%= " #{current_user.username} " %>
 </div>
<%= form_with model:@board, method: :post, local: true do |f| %>
    <div class="field">
        <p><%= f.label :title %></p>
        <%= f.text_field :title %>
    </div>
    <div class="action">
        <%= f.submit %>
    </div>
<% end %>

app/views/boards/show.html.erb
<%= link_to 'スレッド一覧に戻る', boards_path %>
<hr>
<h3><%= @board.title %></h3>
<%= link_to '編集', edit_board_path(@board.id) %>
<%= link_to '削除', board_path(@board.id), method: :delete, data: {confirm: 'OK?'} %>
<hr>
<%= form_with model:@comment, url: board_comments_path(@board, @comment), method: :post, local: true do |f| %>
    <div class="field">
        <%= f.text_area :comment %>
    </div>
    <div class="action">
        <%= f.submit :comment %>
    </div>
<% end %>
<% @comment.reverse.each do |comment| %>
    <p><%= l(comment.created_at, format: :long) %></p>
    <p><%= comment.comment %></p>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/home/index.html.erb
<% if !user_signed_in? %> 
  <div class="sign">
    <div class="sign-in">
      <h3>競馬チャンネル会員の方</h3>
      <p>既にnetkeiba会員の方は、こちらからログインしてください。</p>
      <button><%= link_to 'ログイン', new_user_session_path %></button>
    </div>
    <div class="sign-up">
      <h3>競馬チャンネル会員でない方</h3>
      <p>netkeiba会員でない方は、こちらから無料会員登録をお願いします。</p>
      <button><%= link_to '新規登録', new_user_registration_path %></button>
    </div>
  </div>
<% else %>
  <div class="sign-out">
    <button><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></button>
  </div>
<% end %>

app/views/horses/index.html.erb
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>性別</th>
      <th>通算成績</th>
    </tr>
  </thead>
  <tbody>
    <% @horses.each do |horse| %>
      <tr>
        <td><%= horse.name %></td>
        <td><%= horse.sex %></td>
        <td><%= horse.result %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/log/edit.html.erb
<h1>Log#edit</h1>
<p>Find me in app/views/log/edit.html.erb</p>

app/views/log/index.html.erb
<h1>Log#index</h1>
<p>Find me in app/views/log/index.html.erb</p>

app/views/log/new.html.erb
<h1>Log#new</h1>
<p>Find me in app/views/log/new.html.erb</p>

app/views/log/show.html.erb
<h1>Log#show</h1>
<p>Find me in app/views/log/show.html.erb</p>

app/views/users/show.html.erb
<div class="mypage">
    <div class="mypage-top">
        <h3>マイページトップ</h3>
        <button><%= link_to 'プロフィール編集', edit_user_registration_path %></button>
    </div>
    <div class="mypage-info">
        <div class="mypage-img"></div>
        <div>
            <%= "ようこそ #{current_user.username} さん" %>
        </div>
        <div>
            <%= "Email : #{current_user.email}" %>
        </div>
    </div>
    <div class="mypage-log">
        <%= form_with model:@log, url: { :controller => :logs, :action => :create}, local: true do |f| %>
            <div class="field">
                <%= f.label :diary %>
                <%= f.text_field :diary %>
            </div>
            <div class="action">
                <%= f.submit %>
            </div>
        <% end %>
    </div>
    <div class="mypage-diary">
        <h4>最近のひとこと</h4>
        <% current_user.logs.each do |log| %>
            <div>
                <p><%= l(log.created_at, format: :long) %></p>
                <p><%= log.diary %></p>
                <p><%= link_to '削除', log_path(log.id), method: :delete, data: {confirm: 'OK?'} %></p>
            </div>
        <% end %>
    </div>
</div>

<button><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></button>